### ISSUE TITLE
Editor, run parameter synthesis

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#4]
`Editor.PopUp.ProgressBar.add(run parameter synthesis.click) `

Add PopUp Progress Bar on "run parameter synthesis"

=====================================================
LEGEND:
ModulesDict:= {Model editor:Editor,Model explorer:Explorer,Result explorer:Result}

**Comment by martindemko** [comment]
this is not possible because parameter synthesis is running independently, but there will be some text in progress bar appearing during the process so user could see if it's still running and there will be some kind of event after parameter synthesis to show user that process is done (maybe a PopUp MessageWindow)
